[[redirects]]
from = "/api/*"
to = "http://localhost:8080/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
command = "java -jar idea_rt.jar"
publish = "build/libs"

[build]
command = "gradle build"
publish = "build/libs"